languageCode = "fr"
theme = "laurannehery"
title = "Lauranne Héry – Portfolio"
baseurl = "https://www.laurannehery.fr/"
disableKinds = ["RSS", "section", "taxonomy"]
enableRobotsTXT = false
removePathAccents = true

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Portfolio de Lauranne Héry, conceptrice-rédactrice indépendante"
  [params.author]
  name = "Lauranne Héry"
  occupation = "Conceptrice-rédactrice indépendante"

[permalinks]
page = "/:slug/"
project = "/portfolio/:slug/"
